
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    working_directory: /tmp/src/gifti_clib
    steps:
      - run:
          name: Install required software
          command: |
            apt-get update && apt-get install -y -q eatmydata \
            && eatmydata apt-get update && apt-get install -y -q  \
            cmake \
            gcc \
            git \
            libexpat1-dev \
            make \
            wget \
            zlib1g-dev \
      - checkout


      - run:
          name: Install nifti manually for now
          command: |
            cd /tmp
            git clone --single-branch --branch master https://github.com/NIFTI-Imaging/nifti_clib.git
            d=nifti_build;mkdir $d;cd $d
            cmake -DDOWNLOAD_TEST_DATA=OFF -DBUILD_SHARED_LIBS=ON ../nifti_clib
            make install

      - run:
          name: Build and test gifti, when nifti1 is used
          command: |
            d=../build_nifti1;mkdir $d;cd $d
            cmake ../gifti_clib \
                -DUSE_NIFTI2_CODE=OFF \
                -DUSE_SYSTEM_NIFTI=ON \
                -DDOWNLOAD_TEST_DATA=OFF
            make
            ctest --output-on-failure -LE NEEDS_DATA

      - run:
          name: Build and test gifti, with install
          command: |
            d=../build;mkdir $d;cd $d
            cmake ../gifti_clib \
                -DTEST_INSTALL=OFF \
                -DUSE_SYSTEM_NIFTI=ON \
                -DDOWNLOAD_TEST_DATA=OFF
            make install
            ctest --output-on-failure -LE NEEDS_DATA
            # Check installed gifti_tool has linked correctly
            gifti_tool

      - run:
          working_directory: /tmp/src/gifti_clib
          name: Build with downloads, and use a prefix
          command: |
            export CMAKE_VER=3.11.3
            wget -P /opt/cmake  https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/cmake-${CMAKE_VER}-Linux-x86_64.tar.gz
            cd /opt/cmake
            tar xzvf cmake-${CMAKE_VER}-Linux-x86_64.tar.gz 1> /dev/null
            export PATH="/opt/cmake/cmake-${CMAKE_VER}-Linux-x86_64/bin:$PATH"
            cd -
            d=../build_with_cmake_v11;mkdir $d;cd $d
            cmake ../gifti_clib -DNIFTI_PACKAGE_PREFIX=test_
            make
            ctest --output-on-failure





  # macos_build:
  #   macos:
  #       xcode: "11.2.1"
  #   steps: # a series of commands to run
  #     - checkout
  #     - run:
  #         name: Setup on macos
  #         command: |
  #           brew install expat cmake make
  #     - run:
  #         name: Build on macos
  #         command: |
  #           mkdir ../build
  #           cd ../build
  #           cmake ../gifti_clib
  #           make
  #           ctest --output-on-failure


workflows:
  version: 2
  gifti_build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: /doc\/.*/
            tags:
              only: /.*/
      # - macos_build:
      #     filters:
      #       branches:
      #         ignore: /doc\/.*/
      #       tags:
      #         only: /.*/

